[package]
name = "opensky_downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
bson = "2.11.0"
csv = "1.3.0"
reqwest = { version = "0.12.4", features = ["blocking"] }
serde = { version = "1.0.203", features = ["derive"] }
