[package]
name = "opensky_downloader"
version = "1.2.0"
edition = "2021"

[dependencies]
bson = "2.11.0"
colored = "2.1.0"
csv-async = { version = "1.3.0", features = ["tokio"] }
futures = "0.3.30"
indicatif = { version = "0.17.8", features = ["tokio"] }
mongodb = { version = "2.8.2", features = ["tokio-sync"] }
reqwest = { version = "0.12.5", features = ["stream"] }
serde = { version = "1.0.203", features = ["derive"] }
tokio = { version = "1.38.0", default-features = false, features = ["sync"] }
tokio-util = { version = "0.7.11", features = ["io"] }
