[package]
name = "opensky_downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
bson = "2.11.0"
colored = "2.1.0"
csv = "1.3.0"
mongodb = { version = "2.8.2", features = ["tokio-sync"] }
reqwest = { version = "0.12.4", features = ["blocking"] }
serde = { version = "1.0.203", features = ["derive"] }
